// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FileProcessor.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class Update_Expense : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Name",
                table: "Expenses",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Name",
                table: "Expenses");
        }
    }
}
